In [1]:
import pandas as pd
import numpy as np

performance_metrics = pd.read_csv("performance_metrics.csv")
var_df = pd.read_csv("var_metrics.csv")

ranking_df = performance_metrics.merge(
    var_df,
    on="amfi_code"
)

ranking_df.head()

,amfi_code,mean,std,annual_volatility,annual_return,sharpe_ratio,cagr,VaR_95
0,100016,0.000142,0.009164,0.145481,0.035683,-0.167148,0.026371,-0.014364
1,100025,0.000170,0.002460,0.039052,0.042854,-0.439062,0.044582,-0.003793
2,100033,0.001080,0.011929,0.189367,0.272111,1.120102,0.301232,-0.019034
3,101206,0.000852,0.009177,0.145682,0.214647,1.061535,0.235384,-0.013282
4,101207,0.000424,0.016251,0.257973,0.106962,0.182043,0.079388,-0.026021

In [2]:
def risk_category(volatility):
    if volatility < 0.10:
        return "Low Risk"
    elif volatility < 0.20:
        return "Medium Risk"
    else:
        return "High Risk"

ranking_df["risk_category"] = ranking_df["annual_volatility"].apply(
    risk_category
)

ranking_df[
    ["amfi_code","annual_volatility","risk_category"]
].head()

   amfi_code  annual_volatility risk_category
0     100016           0.145481   Medium Risk
1     100025           0.039052      Low Risk
2     100033           0.189367   Medium Risk
3     101206           0.145682   Medium Risk
4     101207           0.257973     High Risk

In [3]:
ranking_df["recommendation"] = np.where(
    (ranking_df["sharpe_ratio"] > 1) &
    (ranking_df["cagr"] > 0.15),
    "Recommended",
    "Not Recommended"
)

ranking_df[
    ["amfi_code","sharpe_ratio","cagr","recommendation"]
].head()

   amfi_code  sharpe_ratio      cagr   recommendation
0     100016     -0.167148  0.026371  Not Recommended
1     100025     -0.439062  0.044582  Not Recommended
2     100033      1.120102  0.301232      Recommended
3     101206      1.061535  0.235384      Recommended
4     101207      0.182043  0.079388  Not Recommended

In [4]:
recommended_funds = ranking_df[
    ranking_df["recommendation"] == "Recommended"
]

recommended_funds = recommended_funds.sort_values(
    by="sharpe_ratio",
    ascending=False
)

recommended_funds[
    ["amfi_code",
     "sharpe_ratio",
     "cagr",
     "risk_category"]
].head(10)

    amfi_code  sharpe_ratio      cagr risk_category
34     148567      1.483518  0.309741   Medium Risk
30     120843      1.338216  0.309075   Medium Risk
36     148569      1.263220  0.319495   Medium Risk
19     119551      1.244653  0.258047   Medium Risk
25     120505      1.206020  0.328274   Medium Risk
38     149323      1.160297  0.295811   Medium Risk
2      100033      1.120102  0.301232   Medium Risk
9      118632      1.116999  0.240495   Medium Risk
3      101206      1.061535  0.235384   Medium Risk
24     120504      1.061334  0.232951   Medium Risk

In [5]:
recommended_funds.to_csv(
    "recommended_funds.csv",
    index=False
)

print("Recommended Funds Saved Successfully")

Recommended Funds Saved Successfully

In [6]:
recommended_funds.to_csv(
    "recommended_funds.csv",
    index=False
)

print("Recommended Funds Saved Successfully")

Recommended Funds Saved Successfully

In [7]:
print("Total Recommended Funds:", len(recommended_funds))

Total Recommended Funds: 11